<div class="row">
            <div class="col-md-3 border border-light" id="side-menu">
                <div class="row" id="bookmark-column">
                    <div class="col-md-3 border border-danger">
                        
                    </div>
                    <div class="col-md-6 border border-danger">
                        <span class="small-text">Robenta Ahimie <br> <p class="grey-text">Project Manager</p> </span>
                    </div>
                    <div class="col-md-3 border border-danger">
                        <i class="fa-solid fa-bookmark"></i>            
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <h6>Dashboard</h6>
                    </div>
                    <div class="col-md-3 float-start border border-danger">
                        <i class="fa-solid fa-house"></i>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <p class="text-center">
                    ahflajfla Lorem ipsum, dolor sit amet consectet
                    ur adipisicing elit. Fugit quo consequatur sim
                    ilique pariatur impedit, voluptates qui quidem o
                    dit rem culpa minus est deleniti ducimus facilis
                </p>
            </div>
        </div>









        ::::::::::::::
        <div class="container px-0 border">
            <div class="row " id="side-menu">
                <!-- one -->
                <div class="col-md-12">
                    <div class="row" id="bookmark-column">
                        <div class="col-md-3">
                            <div class="overflow-hidden rounded-circle h-50 w-25">
                                <img src="/assets/img/headshot.png" class="img-thumbnail img-fluid" alt="">
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="">
                                <span class="small-text">Robenta Ahimie <br> <p class="grey-text">Project Manager</p> </span>
                            </div>
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
                <!-- 2 -->
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="">
                                <h6>Dashboard</h6>
                            </div>
                        </div>
                        <div class="col-md-7"></div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
            </div>
        </div>


        :::::::::::::

        // const divForNewIcon = document.createElement('div')
        // divForNewIcon.className = 'd-grid justify-content-center'

        // newIcon.innerHTML = '<i class="fa-solid fa-layer-group" style="color: #ba75ff;"></i>'